### ISSUE TITLE
Saving at the top of a block

### ISSUE THREAD

**Issue by Bobgon2020** [CG-Tespy/Fungus-Slot-based-Save-System#1]
A small issue, almost non-existent. When you try to place the "Invoke Method" command, in order to use the AddSave Method as a part of the Save Manager component, at the top of a block as the first command and then try to load it, this error returns: 

Error: Exception has been thrown by the target of an invocation.
UnityEngine.Debug:LogError(Object)
Fungus.InvokeMethod:OnEnter() (at Assets/Fungus/Scripts/Commands/InvokeMethod.cs:302)
Fungus.Command:Execute() (at Assets/Fungus/Scripts/Components/Command.cs:137)
Fungus.<Execute>d__54:MoveNext() (at Assets/Fungus/Scripts/Components/Block.cs:293)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Fungus.Call:OnEnter() (at Assets/Fungus/Scripts/Commands/Call.cs:110)
Fungus.Command:Execute() (at Assets/Fungus/Scripts/Components/Command.cs:137)
Fungus.<Execute>d__54:MoveNext() (at Assets/Fungus/Scripts/Components/Block.cs:293)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Fungus.Flowchart:ExecuteBlock(Block, Int32, Action) (at Assets/Fungus/Scripts/Components/Flowchart.cs:593)
CGTUnity.Fungus.SaveSystem.FlowchartLoader:LoadExecutingBlocks(FlowchartData, Flowchart) (at Assets/[CGT] Fungus Slot-based Save System/Scripts/LoaderTypes/FlowchartLoader.cs:132)
CGTUnity.Fungus.SaveSystem.FlowchartLoader:Load(FlowchartData) (at Assets/[CGT] Fungus Slot-based Save System/Scripts/LoaderTypes/FlowchartLoader.cs:33)
CGTUnity.Fungus.SaveSystem.SaveLoader`1:Load(SaveDataItem) (at Assets/[CGT] Fungus Slot-based Save System/Scripts/LoaderTypes/SaveLoader.cs:38)
CGTUnity.Fungus.SaveSystem.GameLoader:LoadState(GameSaveData) (at Assets/[CGT] Fungus Slot-based Save System/Scripts/LoaderTypes/GameLoader.cs:97)
CGTUnity.Fungus.SaveSystem.<>c__DisplayClass2_0:<Load>b__0(Scene, LoadSceneMode) (at Assets/[CGT] Fungus Slot-based Save System/Scripts/LoaderTypes/GameLoader.cs:48)
UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded(Scene, LoadSceneMode)

No big deal though, just have it be the second or third command and you should be fine.

3/4/2020 ADDENDUM: In addition to having the invoke save command be in second place to a first command you also have to have it under a 'Set Menu Dialog' command for some reason in order to avoid the aforementioned error.  So far I have only been able to save once using the AddSave(Int32, Boolean) method; any subsequent saves will fail to overwrite the first thus any attempt to load using the same method will load the first save alone.

**Comment by CG-Tespy** [comment]
The issue has been fixed in the master branch, though said issue is replaced by one that simply freezes the game. I've updated the Known Issues page in regards to it. https://github.com/CG-Tespy/Fungus-Slot-based-Save-System/wiki/Known-Issues

**Comment by CG-Tespy** [comment]
@Bobgon2020 The issue should be fixed in version 1.06, the latest version as of this writing.
