### ISSUE TITLE
Same info (date) for all save slots

### ISSUE THREAD

**Issue by adrianhm13** [CG-Tespy/Fungus-Slot-based-Save-System#11]
Hello, I noticed now that when I save the game or load it I see the same information in the field date, I mean all the saves are saved at 5 february 15:00 for example. Not sure if I screwed up or its a bug

**Comment by CG-Tespy** [comment]
I checked just now, and it works fine on my end. Are there any errors showing up in the console? If they're related to the scripts in the save system, perhaps I can help you.

**Comment by adrianhm13** [comment]
Hello there, I only get this warning.

If it helps this its what exactly happens: I save in the slot, the time shows correctly, and if I still playing and loading everything looks fine, when I close the game and open again, all the slots information automatically are changed to the exact time when I open the load menu.

After Load Beginning cannot be called/executed, it is already running.
UnityEngine.Debug:LogWarning(Object)
Fungus.Flowchart:ExecuteBlock(Block, Int32, Action) (at C:/Users/Adrian/The Diary/Assets/Fungus/Scripts/Components/Flowchart.cs:588)
Fungus.EventHandler:ExecuteBlock() (at C:/Users/Adrian/The Diary/Assets/Fungus/Scripts/Components/EventHandler.cs:82)
CGTUnity.Fungus.SaveSystem.SaveDataLoaded:OnSaveDataLoaded(String) (at C:/Users/Adrian/The Diary - copia/Assets/[CGT] Fungus Slot-based Save System/Scripts/Utils/SaveDataLoaded.cs:28)
CGTUnity.Fungus.SaveSystem.SaveDataLoaded:NotifyEventHandlers(String) (at C:/Users/Adrian/The Diary - copia/Assets/[CGT] Fungus Slot-based Save System/Scripts/Utils/SaveDataLoaded.cs:41)
CGTUnity.Fungus.SaveSystem.FlowchartLoader:Load(FlowchartData) (at C:/Users/Adrian/The Diary - copia/Assets/[CGT] Fungus Slot-based Save System/Scripts/LoaderTypes/FlowchartLoader.cs:34)
CGTUnity.Fungus.SaveSystem.SaveLoader`1:Load(SaveDataItem) (at C:/Users/Adrian/The Diary - copia/Assets/[CGT] Fungus Slot-based Save System/Scripts/LoaderTypes/SaveLoader.cs:38)
CGTUnity.Fungus.SaveSystem.GameLoader:LoadState(GameSaveData) (at C:/Users/Adrian/The Diary - copia/Assets/[CGT] Fungus Slot-based Save System/Scripts/LoaderTypes/GameLoader.cs:97)
CGTUnity.Fungus.SaveSystem.<>c__DisplayClass2_0:<Load>b__0(Scene, LoadSceneMode) (at C:/Users/Adrian/The Diary - copia/Assets/[CGT] Fungus Slot-based Save System/Scripts/LoaderTypes/GameLoader.cs:48)
UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded(Scene, LoadSceneMode)

**Comment by adrianhm13** [comment]
Any idea? :(

**Comment by CG-Tespy** [comment]
Hm, did you make any changes to the save system's scripts?

**Comment by adrianhm13** [comment]
I changed only the saves folder direction

**Comment by adrianhm13** [comment]
Anyways I only get the warning now, I don't know why those errors show up before,

**Comment by CG-Tespy** [comment]
I've managed to reproduce the issue on my end. I'll be working on it!

**Comment by adrianhm13** [comment]
Nice! I'll be around, thanks!

**Comment by CG-Tespy** [comment]
Please try the package from this link: https://drive.google.com/file/d/1YJ03kukINUobsRkOBVZ9A48YsrfBwzL-/view?usp=sharing
Then try making some new saves. Let me know if any issues arise

**Comment by adrianhm13** [comment]
Works like a charm, thanks a lot! but I see the previous save files are not working, is there a way to make it read them or the player will need to make new saves? thanks!

**Comment by adrianhm13** [comment]
Ops, my bad, it's there but only with null information, thanks a lot for your work!

**Comment by adrianhm13** [comment]
I reopened the issue for a question, sorry for the inconvenience. Could you tell me why it happened if it's possible? to not trigger the problem in the future if it was caused by me. Thanks a lot again!

**Comment by CG-Tespy** [comment]
No worries. Also, you weren't the one at fault for the bug; I was. ^^; It turned out that the old version of the system didn't properly save DateTime objects, which I didn't realize until I decided to look into this particular bug.

If anything, I really appreciate that you brought this to my attention; now, a pretty important feature works as it should ^_^
