### ISSUE TITLE
System not loading actors or changing music

### ISSUE THREAD

**Issue by Randozart** [CG-Tespy/Fungus-Slot-based-Save-System#13]
I downloaded the package and got the system to work. It succesfully loads the dialogue from the point I saved it at. However, it does not seem to load those elements from the flowchart that simply add a persistent element to the scene, like an actor unto a stage or the music being changed. How can I best resolve this? Is there perhaps a way to key in Fungus' own save system into this one or have I simply overlooked something?

**Comment by CG-Tespy** [comment]
You'll want to use Progress Markers and Save Data Loaded Events. See the tutorial here: https://github.com/CG-Tespy/Fungus-Slot-based-Save-System/wiki/Progress-Marker-Tutorial

**Comment by Randozart** [comment]
Thank you very much for the rapid response. It seems to work, and I can see it offers a great many additional options over Fungus' built in features. Thank you very much for having developed this!
