### ISSUE TITLE
Problem with images

### ISSUE THREAD

**Issue by Jailbait228** [CG-Tespy/Fungus-Slot-based-Save-System#14]
Hi, thank you for your code. I tried to make "fade to view" after loading (to save image)  by using marker keys but i have an error .
"The object of type 'View' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object."
So how can i load my view with loading game?
if i use this with "set say dialog" i have
"StackOverflowException
UnityEngine.Transform.get_position () (at <c7864a0eaeb24b2a999fb177623d54b4>:0)
Fungus.CameraManager+<>c__DisplayClass27_0.<FadeToView>b__0 () (at ..."
![image](https://user-images.githubusercontent.com/61063262/128037867-89104da0-4a48-493b-8c2f-cc57dc7aff1c.png)

**Comment by CG-Tespy** [comment]
Please provide steps on reproducing the problem

**Comment by Jailbait228** [comment]
So, i use fungus view to have an image in my game. 
![image](https://user-images.githubusercontent.com/61063262/128139335-5114f373-a15f-4856-883d-b6a1cc1ef208.png)

If i want to see my picture in chene i use command "Fade to view". 
![image](https://user-images.githubusercontent.com/61063262/128139521-96f3a4da-2c24-4c97-b011-8d069fd4715d.png)

So the game will look like
![image](https://user-images.githubusercontent.com/61063262/128139712-ed777b33-b379-4a3c-9168-417352adbaed.png)

If i want to load my game from save i need to return my image to scene. I think that i should use "Fade to View" again.
![image](https://user-images.githubusercontent.com/61063262/128140098-89f9723b-f9a1-4231-b786-1d57bd93f10b.png)

But i have an error. 
![image](https://user-images.githubusercontent.com/61063262/128140456-b775f0f7-75a6-44ba-a5af-a7cb0273afc4.png)

Maybe i should use another method?

**Comment by CG-Tespy** [comment]
Interesting... It seems that the camera manager has an issue with doing things like panning right as a scene loads. My save system doesn't even touch any of the camera APIs, so this must be mainly an issue with Fungus itself.

I managed to avoid the problem on my end by adding a Wait Frames Command (set to wait just 1 frame) right before the Fade To View command. Please try that and let me know how it goes.

**Comment by Jailbait228** [comment]
yes, everything is working, thanks for help)))
