### ISSUE TITLE
Problem loading menu dialog

### ISSUE THREAD

**Issue by moepivo** [CG-Tespy/Fungus-Slot-based-Save-System#19]
Hi!  I'm using your save system and I'm having the same problem. I'm creating a visual novel. When I save the game progress in the dialogue menu, nothing happens when loading this save. Moreover, saving works fine in all other cases, portraits, say dialogue and backgrounds are loaded, but there is no dialogue menu. help me please!!!!!

**Comment by CG-Tespy** [comment]
Sorry for the late response. Can you send a version of the project with the custom assets removed, as well as instructions on replicating the bug?

**Comment by moepivo** [comment]
I'm not very good at this, but I hope I can help...I didn't quite understand what you mean, sorry.
Here is the version (I hope this is what you need) and the errors that occur (which don’t seem to relate to the problem, but I hope it helps)
And this is what loading in the elections looks like...
![Unity_5HhhkB0tyt](https://github.com/CG-Tespy/FungusSlotBasedSaveSystem_Unity/assets/169723975/85c9baf2-8dcd-43bd-8f54-84f3e876c42c)
![Unity_Hub_3LSOYkefTM](https://github.com/CG-Tespy/FungusSlotBasedSaveSystem_Unity/assets/169723975/442be66c-0ecb-4724-b6b1-c7b8fc869319)
![Unity_xQZrYQOYUN](https://github.com/CG-Tespy/FungusSlotBasedSaveSystem_Unity/assets/169723975/9a77899d-285e-4738-8b6e-c3612e321564)

![Unity_BfPIS8Y3nV](https://github.com/CG-Tespy/FungusSlotBasedSaveSystem_Unity/assets/169723975/ce94bad1-939e-472e-a558-bd976fdbc306)

**Comment by CG-Tespy** [comment]
Sorry for the late reply. When I said "version of the project", I meant a copy of the project. In this case, one without your custom assets (unless you're okay with just anyone being able to access said assets)
