### ISSUE TITLE
Beginner to fungus need help !!

### ISSUE THREAD

**Issue by Zapas007** [CG-Tespy/Fungus-Slot-based-Save-System#3]
Hello there , 
Im really new to fungus and pretty much have no knowledge of coding and stuff 
I was looking for a saving system and i found this  one and it looks pretty interesting the only thing is that i dont have any slight idea how to use it or how to implement it in my game cause im new to fungus and coding , so if its possible can anyone give me some simple steps how to use it please its really needed!!! 
thanks.

**Comment by CG-Tespy** [comment]
Take a look at [the wiki pages](https://github.com/CG-Tespy/Fungus-Slot-based-Save-System/wiki). If anything is unclear, please post a reply in this thread; I'll do my best to clear things up :)

**Comment by CG-Tespy** [comment]
It's been about two weeks without any responses. If you still need help with anything, please create a new Issue.
