### ISSUE TITLE
Cannot for the life of me, figure out how to use this

### ISSUE THREAD

**Issue by Sunkrishta** [CG-Tespy/Fungus-Slot-based-Save-System#4]
I am creating a visual novel in Unity using Fungus. The save system in my game should be relatively simple to implement yet I cant figure out how to do it. saving will only be done from one place (main characters room) and Loading will only done from the main menu. The only thing that needs to be saved is the variables of which all are marked as global. I do need multiple slots though so I figured id give this a go. When trying to load the prefabs into my scene, I see nothing but outlines. I don't seem to be able to attach anything to buttons etc. Am I missing something here? Does this not work with Unity 2020.1.0f1? I read through the documentation on the wiki last night and I just couldn't figure out how to implement this. Did I miss something?

Edit. Apparently I am an idiot and only downloaded part of the code. I was able to get it all but was left with a wall of errors upon importing to Unity 2020.1.0f1
[Errors.txt](https://github.com/CG-Tespy/Fungus-Slot-based-Save-System/files/5066566/Errors.txt)

**Comment by Sunkrishta** [comment]
I figured it out. Sorry

**Comment by CG-Tespy** [comment]
No problem, I'm actually glad you reached out :)
