### ISSUE TITLE
Keeping view and sound information when Loading

### ISSUE THREAD

**Issue by TessaNicholson** [CG-Tespy/Fungus-Slot-based-Save-System#9]
Hello , first of all I wanted to thank you for creating this system , I'm currently doing a student video game project by myself with fungus and this is a life saver. Also, forgive me if I make any spelling mistake written in this message , english is not my first language. 

I have been able to set up the system correctly  thank to your exemple scenes. When I try it in unity or in a build, the system works , it load the text wich I wanted to save. But it does not retain any illustration or music that is supposed to show at the same time. 

Is it because the save system work in a way where it only load one specific action in the flowchart and ignore all previous action 
 ? Or did I set it up wrong ? 

If it is meant to be that way, is there any way for the saving manager to memorize what's the screen is showing and what song is playing at the moment  for it to be load later ? 

Thank you in advance for your response.

**Comment by CG-Tespy** [comment]
Yes, there is a way to have the music and illustrations retained: it is the
Progress Marker system. See here:
https://github.com/CG-Tespy/Fungus-Slot-based-Save-System/wiki/Progress-Marker-Tutorial

If you have any questions, please let me know :)

**Comment by CG-Tespy** [comment]
Closing this since it hasn't had a response in 3 weeks. Feel free to email me or post another Issue if you need more help
